services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    network_mode: host
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    network_mode: host
    depends_on:
      - backend
    restart: unless-stopped
